# Build the Go Binary.
FROM golang:1.26.2-alpine AS build_sales
ENV CGO_ENABLED=0
ARG BUILD_REF

# Create the service directory and the copy the module files first and download
# dependencies to take advantage of Docker's caching.
RUN mkdir /service
COPY go.* /service/
WORKDIR /service
RUN go mod download

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service/api/services/sales
RUN go build -ldflags "-X main.build=${BUILD_REF}"


# Run the Go Binary in Alpine.
FROM alpine:3.21
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S sales && \
    adduser -u 1000 -h /service -G sales -S sales
COPY --from=build_sales --chown=sales:sales /service/api/services/sales/sales /service/sales
WORKDIR /service
USER sales
CMD ["./sales"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="Haseeb <haseeb@example.com>" \
      org.opencontainers.image.revision="${BUILD_REF}"
